image: Visual Studio 2013

version: "{build}"

skip_tags: true
clone_depth: 10

platform:
  - x64

install:
  - curl -L -o atom-windows.zip https://github.com/atom/atom/releases/download/v1.19.0/atom-x64-windows.zip
  - curl -L -o pty.js.zip https://github.com/platformio/pty.js/archive/prebuilt.zip
  - 7z x -y atom-windows.zip -oC:\AtomSrc
  - 7z x -y pty.js.zip -opty.js
  - SET PATH=C:\AtomSrc\Atom x64\resources\app\apm\bin;%PATH%  
  - echo %PATH%
  - dir C:\Program Files (x86)\MSBuild

build_script:
  - dir
  - cd pty.js/pty.js-prebuilt
  - node --version
  - apm --version
  - npm --version
  - where npm
  - npm install
  - dir build\Release
  
deploy: off
artifacts:
  - path: pty.js\pty.js-prebuilt\build\Release\pty.node
    name: pty.node
  - path: pty.js\pty.js-prebuilt\build\Release\winpty-agent.exe
    name: winpty-agent.exe
  - path: pty.js\pty.js-prebuilt\build\Release\winpty.dll
    name: winpty.dll    
