image: Visual Studio 2015

version: "{build}"

skip_tags: true
clone_depth: 10

platform:
  - x86

install:
  - curl -L -o atom-x64-windows.zip https://github.com/atom/atom/releases/download/v1.14.0-beta4/atom-x64-windows.zip
  - curl -L -o pty.js.zip https://github.com/platformio/pty.js/archive/prebuilt.zip
  - 7z x -y atom-x64-windows.zip -oC:\AtomSrc
  - 7z x -y pty.js.zip -opty.js
  - SET PATH=C:\AtomSrc\resources\app\apm\bin;%PATH%  

build_script:
  - dir
  - cd pty.js
  - dir
  - npm install
